title: Bitemetrics
description: When good meals meet good feels.

remote_theme: just-the-docs/just-the-docs   
logo: "/assets/images/logo.png"

url: "https://kenjigunawan.github.io"  
baseurl: "/bitemetrics"                

aux_links:
  Bitemetrics Repo: https://github.com/kenjigunawan/bitemetrics