title: Gas or Pass?
description: An Algorithm for Deliciousness

theme: just-the-docs 
logo: "/assets/images/gas or pass.svg"

url: "https://kenjigunawan.github.io"  
baseurl: "/gasorpass"                

aux_links:
  Bitemetrics Repo: https://github.com/kenjigunawan/gasorpass